### ISSUE TITLE
`Cannot read property 'contents' of undefined` when processing `yeoman.png`

### ISSUE THREAD

**Issue by Byron** [imagemin/imagemin#129]
When running `grunt imagemin` on a newly created *yeoman-angular* project, it seems to be unable to process the default image provided with the scaffolding.

![yeoman](https://cloud.githubusercontent.com/assets/63622/10558661/a4e390b2-74d8-11e5-87cf-31a2aa22e1b1.png)

# How to reproduce 

```bash
$ git clone https://github.com/Byron/katars && cd katars
$ git checkout c8431de
$ npm update
$ grunt imagemin
```

# Meta

Running on `OS X 10.11 (15A284)`.
```bash
✗ npm ls imagemin
katars@ /private/tmp/katars
└─┬ grunt-contrib-imagemin@0.9.4
  └── imagemin@3.2.0
✗ node -v
v4.2.1
✗ npm -v
2.14.7
```

**Comment by Byron** [comment]
Thanks ! That was fast.
Could you advise me on how to make use of the fix ?

**Comment by shinnn** [comment]
I'm preparing for imagemin v3.2.1. Please wait a moment.

**Comment by shinnn** [comment]
Ahh, I forgot [I don't have a permission to publish new imagemin to npm](https://www.npmjs.com/package/imagemin/access).

Please wait until @kevva or @sindresorhus publishes a new version.

**Comment by shinnn** [comment]
For now you can directly install the fixed commit. 66efa569319829bbd19bdede818c328df8e8c6ed

```
npm install imagemin/imagemin#66efa569319829bbd19bdede818c328df8e8c6ed
```

**Comment by sindresorhus** [comment]
@shinnn I'm afk, but you have publish rights to `imagemin` now.

@kevva Can you add @shinnn to all the imagemin packages on npm?

**Comment by shinnn** [comment]
@sindresorhus Thanks. I just published v3.2.1.

@Byron Reinstall `imagemin` and you can get a fixed version.

**Comment by Byron** [comment]
@shinnn Thank you. For some reason, I didn't see a new version on NPM, also the package.json in this project didn't change and still claims to be `v3.2.0`. Am I missing something ?

**Comment by shinnn** [comment]
> I didn't see a new version on NPM

```
$ npm view imagemin version
> 3.2.1
```

On my Mac OS X I can install v3.2.1 with `npm i -S imagemin`.

> the package.json in this project didn't change and still claims to be `v3.2.0`

Here is the `v3.2.1` branch. https://github.com/imagemin/imagemin/releases/tag/v3.2.1

**Comment by Byron** [comment]
Oh, that's how it's done ! I have been looking at [this site](https://www.npmjs.com/package/imagemin), which is still showing the previous version it seems.

Thanks for all the support, but for some reason, I can't make `grunt-contrib-imagemin` pickup the latest version. I just deleted my node_modules folder and retried, with no avail.

**Comment by shinnn** [comment]
>  I can't make `grunt-contrib-imagemin` pickup the latest version.

Weird. The latest `grunt-contrib-imagemin` requires `imagemin ^3.1.0`, and the semver range `^3.1.0` matches `3.2.1`.

**Comment by Byron** [comment]
I have to correct myself: 
```bash
➜  katars git:(master) ✗ npm ls | grep imagemin
├─┬ grunt-contrib-imagemin@0.9.4
│ ├─┬ imagemin@3.2.1
│ │ ├─┬ imagemin-gifsicle@4.2.0
│ │ ├─┬ imagemin-jpegtran@4.3.1
│ │ ├─┬ imagemin-optipng@4.3.0
│ │ ├─┬ imagemin-svgo@4.1.2
```
It actually picked it up, but the bug does not seem to be fixed. I can still reproduce it.

**Comment by shinnn** [comment]
I cannot reproduce `Cannot read property 'contents' of undefined` error.

```js
'use strict';

module.exports = function(grunt) {
	grunt.initConfig({
	  imagemin: {
	    png: {
	      src: ['yeoman.png'], // same image as https://cloud.githubusercontent.com/assets/63622/10558661/a4e390b2-74d8-11e5-87cf-31a2aa22e1b1.png
	      dest: 'yeoman-optimized.png'
	    }
	  }
	});

	grunt.loadNpmTasks('grunt-contrib-imagemin');
	grunt.registerTask('default', ['imagemin']);
};
```

```
$ node -v
v4.2.1
$ npm -v
3.3.8
$ npm ls grunt-contrib-imagemin
test@1.0.1 /Users/Shinnosuke/github/test
└─┬ grunt-contrib-imagemin@0.9.4
  └── imagemin@3.2.1 
$ grunt
Running "imagemin:png" (imagemin) task
Minified 1 image (saved 5.01 kB)

Done, without errors.
```

**Comment by Byron** [comment]
Thanks again ! With the minimal example you provided, it worked for me as well.

What I ended up doing is to replace the `grunt-contrib-imagemin` directory in my actual project with the one from the minimal example. That way, I would end up with the correct version.

It is unclear to me why I wasn't seeing the correct version in the actual project after removing `node_modules` and installing from scratch.

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin/issues/129#issuecomment-148917349

@kevva Can you add @shinnn to all the imagemin packages on npm?

And, could you add me to [decompress](https://github.com/kevva/decompress) and [gulp-decompress](https://github.com/kevva/gulp-decompress) on npm? Currently some users have difficulty in installing imagemin. https://github.com/kevva/download/issues/81

**Comment by kevva** [comment]
@shinnn, added you to `decompress` and `gulp-decompress`. I'll add you to the remaining imagemin packages tomorrow!

**Comment by shinnn** [comment]
> Thanks for maintaining those modules in my absence :).

:smile: Again https://github.com/imagemin/pngcrush-bin/commit/54f2f5899e02ccf9e455e05a84f7a0dda8be67e1#commitcomment-9591493,

> No problem. I'm a heavy user of imagemin as well as a contributor :)

**Comment by billyxs** [comment]
When you create an app with yeoman, using "yo angular", the grunt-contrib-imagemin module will install with the latest imagemin - ^3.1.0.  The grunt build process will encounter the `Cannot read property 'contents' of undefined` error.  

You will need to go into the grunt-contrib-imagemin module, and fix the module to use imagemin@3.1.0

Unfortunately, if you are using a CI tool like Travis, it's difficult to side step the issue without disabling the imagemin build step

**Comment by shinnn** [comment]
You can create a pull request to fix the problem. https://github.com/gruntjs/grunt-contrib-imagemin/pulls

**Comment by Edgar160** [comment]
To manage this to work you need toupdate the  package.json to "grunt-contrib-imagemin": "^1.0.0", this version was released today.

**Comment by linslin** [comment]
:+1: `"grunt-contrib-imagemin": "^1.0.0"` is working fine with `imagemin 4.0.0`! @Edgar160 you saved my day. Cheers

**Comment by voozek** [comment]
Thanks @Edgar160. It works for me too!
